package calendar

import (
	"fmt"
	"time"

	"github.com/charmbracelet/bubbles/key"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
)

type Model struct {
	cursor       int
	initialDay   time.Time
	CurrentDate  time.Time
	SelectedDate time.Time
	// VisibleDates []time.Time
	KeyMap KeyMap
	Styles Styles
}

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	Header     lipgloss.Style
	Cell       lipgloss.Style
	Selected   lipgloss.Style
	InitialDay lipgloss.Style
}

func DefaultStyles() Styles {
	return Styles{
		Header:     lipgloss.NewStyle().Bold(true).Underline(true),
		Cell:       lipgloss.NewStyle().Width(4).Align(lipgloss.Right),
		Selected:   lipgloss.NewStyle().Width(4).Align(lipgloss.Right).Background(lipgloss.Color("62")).Foreground(lipgloss.Color("230")),
		InitialDay: lipgloss.NewStyle().Width(4).Align(lipgloss.Right).Background(lipgloss.Color("62")).Foreground(lipgloss.Color("230")).Bold(true),
	}
}

func (m *Model) SetStyles(s Styles) {
	m.Styles = s
}

// KeyMap defines keybindings. It satisfies to the help.KeyMap interface, which
// is used to render the help menu.
type KeyMap struct {
	Today    key.Binding
	Next     key.Binding
	Previous key.Binding
	LineUp   key.Binding
	LineDown key.Binding
	PageUp   key.Binding
	PageDown key.Binding
}

func DefaultKeyMap() KeyMap {
	return KeyMap{
		Today: key.NewBinding(
			key.WithKeys("t"),
			key.WithHelp("t", "today"),
		),
		Next: key.NewBinding(
			key.WithKeys("→", "l"),
			key.WithHelp("→/l", "next day"),
		),
		Previous: key.NewBinding(
			key.WithKeys("←", "h"),
			key.WithHelp("←/h", "previous day"),
		),
		LineUp: key.NewBinding(
			key.WithKeys("↑", "k"),
			key.WithHelp("↑/k", "previous week"),
		),
		LineDown: key.NewBinding(
			key.WithKeys("↓", "j"),
			key.WithHelp("↓/j", "next week"),
		),
		PageUp: key.NewBinding(
			key.WithKeys("pgup"),
			key.WithHelp("pgup", "previous month"),
		),
		PageDown: key.NewBinding(
			key.WithKeys("pgdn"),
			key.WithHelp("pgdn", "next month"),
		),
	}
}

func New() Model {
	return Model{
		cursor:       0,
		CurrentDate:  time.Now(),
		initialDay:   time.Now(),
		SelectedDate: time.Now(),
		KeyMap:       DefaultKeyMap(),
		Styles:       DefaultStyles(),
	}
}

func (m *Model) SetInitalDay(day time.Time) {
	m.initialDay = day
}
func (m *Model) SetSelectedDay(day time.Time) {
	m.SelectedDate = day
}

func (m Model) Init() tea.Cmd {
	return nil
}

func (m Model) Update(msg tea.Msg) (Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch {
		case key.Matches(msg, m.KeyMap.Today):
			m.SelectedDate = time.Now()
		case key.Matches(msg, m.KeyMap.Next):
			m.SelectedDate = m.SelectedDate.AddDate(0, 0, 1)
		case key.Matches(msg, m.KeyMap.Previous):
			m.SelectedDate = m.SelectedDate.AddDate(0, 0, -1)
		case key.Matches(msg, m.KeyMap.LineUp):
			m.SelectedDate = m.SelectedDate.AddDate(0, 0, -7)
		case key.Matches(msg, m.KeyMap.LineDown):
			m.SelectedDate = m.SelectedDate.AddDate(0, 0, 7)
		case key.Matches(msg, m.KeyMap.PageUp):
			m.SelectedDate = m.SelectedDate.AddDate(0, -1, 0)
		case key.Matches(msg, m.KeyMap.PageDown):
			m.SelectedDate = m.SelectedDate.AddDate(0, 1, 0)
		}
		// Set the current CurrentDate to the first day of the month if the selected date is in a different month
		if m.SelectedDate.Month() != m.CurrentDate.Month() || m.SelectedDate.Year() != m.CurrentDate.Year() {
			m.CurrentDate = time.Date(m.SelectedDate.Year(), m.SelectedDate.Month(), 1, 0, 0, 0, 0, m.SelectedDate.Location())
		}
	}
	return m, nil
}

func (m Model) View() string {
	header := m.Styles.Header.Render(m.CurrentDate.Format("January 2006"))

	// Get the first day of the current month
	firstOfMonth := time.Date(m.CurrentDate.Year(), m.CurrentDate.Month(), 1, 0, 0, 0, 0, m.CurrentDate.Location())

	// Get the weekday of the first day of the month (0 = Sunday, 1 = Monday, ..., 6 = Saturday)
	startOfWeek := int(firstOfMonth.Weekday())

	// Get the last day of the month by adding one month to the first day and subtracting one day
	lastOfMonth := firstOfMonth.AddDate(0, 1, -1).Day()

	// Build the calendar grid
	day := 1

	// Calculate the total cells needed (including empty cells for the start of the month)
	totalCells := startOfWeek + lastOfMonth
	numOfRows := (totalCells + 6) / 7 // Calculate the number of rows needed
	rows := make([]string, numOfRows)

	for row := range numOfRows {
		var cells []string

		for col := range 7 {
			cellIndex := row*7 + col
			if cellIndex < startOfWeek || day > lastOfMonth {
				cells = append(cells, "    ") // Empty cell
			} else if day <= lastOfMonth {
				cellStr := fmt.Sprintf("%2d ", day)
				if m.SelectedDate.Day() == day && m.SelectedDate.Month() == m.CurrentDate.Month() && m.SelectedDate.Year() == m.CurrentDate.Year() {
					cellStr = m.Styles.Selected.Render(cellStr)

				} else if m.initialDay.Day() == day && m.initialDay.Month() == m.CurrentDate.Month() && m.initialDay.Year() == m.CurrentDate.Year() {
					cellStr = m.Styles.InitialDay.Render(cellStr)
				} else {
					cellStr = m.Styles.Cell.Render(cellStr)
				}
				cells = append(cells, cellStr)
				day++
			} else {
				cells = append(cells, "    ") // Empty cell after the last day
			}
		}
		rows[row] = lipgloss.JoinHorizontal(lipgloss.Left, cells...)
	}

	return lipgloss.JoinVertical(
		lipgloss.Top,
		header,
		" Su  Mo  Tu  We  Th  Fr  Sa ",
		lipgloss.JoinVertical(lipgloss.Top, rows...),
	)
}
